#!/bin/bash 

TMPDIR=${TMPDIR:-/tmp}
dbname=$1

echo db is $dbname 
echo options $CDB2_OPTIONS

set -e

run_test() {
    local test_input_file_name=$1

    local test_name
    test_name=$(echo ${test_input_file_name} | cut -d "." -f 1)

    local exp_output_file_name=${test_name}.expected
    local output_file_name=${test_name}.output

    local cmd="cdb2sql -s -f ${test_input_file_name} ${CDB2_OPTIONS} ${dbname} default"
    echo ${cmd} "> ${output_file_name}"
    ${cmd} 2>&1 > ${output_file_name}

    cmd="diff ${exp_output_file_name} ${output_file_name}"
    echo ${cmd}
    if ! ${cmd} > /dev/null; then
        echo "failed ${test_name}"
        echo "see diffs here: ${HOSTNAME}"
        echo "> diff -u ${PWD}/{${exp_output_file_name},${output_file_name}}"
        return 1
    fi
}

main() {
    local failed_test=0

    local test_input_files
    test_input_files=$(find . -name 't[0-9][0-9].sql' -exec basename {} \;)

    local test_input_file_name
    for test_input_file_name in ${test_input_files}; do
        echo "--- Running ${test_input_file_name} ---"
        if run_test ${test_input_file_name}; then
            echo "--- Passed ${test_input_file_name} ---"
        else
            echo "xxx Failed ${test_input_file_name} xxx"
            failed_test=1
        fi
    done

    return ${failed_test}
}

main
