#!/usr/bin/env bash

set -e

default_implementation="modsnap" # "original", "newsi", or "modsnap"
newsi_switches="gbl_new_snapisol gbl_new_snapisol_logging"
modsnap_switches="gbl_use_modsnap_for_snapshot"
modsnap_pit_switch="gbl_modsnap_asof"
newsi_pit_switch="gbl_new_snapisol_asof"

verify_switch_values() {
	local rc=0 switches=$1 exp_on_off=$2
	local info=$(cdb2sql $CDB2_OPTIONS $DBNAME default "exec procedure sys.cmd.send('stat snapconfig')")

	for switch in $switches;
	do
		if ! (echo "$info" | grep --ignore-case "$switch=$exp_on_off" > /dev/null);
		then
			echo "$switch does not have expected value ($exp_on_off): $info"
			return 1
		fi
	done
}

verify_implementation() {
	local rc=0 impl=$1
	local info=$(cdb2sql $CDB2_OPTIONS $DBNAME default "exec procedure sys.cmd.send('stat snapconfig')")

	if ! (echo "$info" | grep --ignore-case "Implementation set to '$impl'" > /dev/null); then
		echo "Snapshot implementation is not expected ('$impl'): $info"
		return 1
	fi
}

check_original_implementation_is_enabled() {
	verify_implementation 'original'
	verify_switch_values "$newsi_switches" "off"
	verify_switch_values "$modsnap_switches" "off"
	verify_switch_values "$modsnap_pit_switch" "off"
	verify_switch_values "$newsi_pit_switch" "off"
}

check_modsnap_implementation_is_enabled() {
	verify_implementation 'modsnap'
	verify_switch_values "$newsi_switches" "off"
	verify_switch_values "$modsnap_switches" "on"
	verify_switch_values "$newsi_pit_switch" "off"

	if (( pit_should_be_enabled == 1 )); then
		verify_switch_values "$modsnap_pit_switch" "on"
	else
		verify_switch_values "$modsnap_pit_switch" "off"
	fi
}

check_newsi_implementation_is_enabled() {
	verify_implementation 'new'
	verify_switch_values "$newsi_switches" "on"
	verify_switch_values "$modsnap_switches" "off"
	verify_switch_values "$modsnap_pit_switch" "off"

	if (( pit_should_be_enabled )); then
		verify_switch_values "$newsi_pit_switch" "on"
	else
		verify_switch_values "$newsi_pit_switch" "off"
	fi

	return $?
}

main() {
	if [ "$TESTCASE" == "siconfig" ];
	then
		local pit_should_be_enabled=1
		check_${default_implementation}_implementation_is_enabled $pit_should_be_enabled
	elif [ "$TESTCASE" == "siconfig_disable_newsi_generated" -a "$default_implementation" != "newsi" ];
	then
		local pit_should_be_enabled=1
		check_${default_implementation}_implementation_is_enabled $pit_should_be_enabled
	elif [ "$TESTCASE" == "siconfig_newsi_generated" ];
	then
		local pit_should_be_enabled=1
		check_newsi_implementation_is_enabled $pit_should_be_enabled
	elif [ "$TESTCASE" == "siconfig_modsnap_generated" ];
	then
		local pit_should_be_enabled=1
		check_modsnap_implementation_is_enabled $pit_should_be_enabled
	elif [ "$TESTCASE" == "siconfig_disable_pit_generated" ];
	then
		local pit_should_be_enabled=0
		check_modsnap_implementation_is_enabled $pit_should_be_enabled
	elif [ "$TESTCASE" == "siconfig_orig_generated" ];
	then
		local pit_should_be_enabled=1
		check_original_implementation_is_enabled $pit_should_be_enabled
	elif [ "$TESTCASE" == "siconfig_orig_after_newsi_generated" ];
	then
		local pit_should_be_enabled=1
		check_original_implementation_is_enabled $pit_should_be_enabled
	elif [ "$TESTCASE" == "siconfig_disable_newsi_generated" && "$default_implementation" == "newsi" ];
	then
		local pit_should_be_enabled=1
		check_original_implementation_is_enabled $pit_should_be_enabled
	else
		echo "No test for $TESTCASE"
		return 1
	fi

	return $?
}

main
exit $?
