[drop table if exists foo] rc 0
[drop table if exists bar] rc 0
[create table foo { schema { int a } keys { "donut" = a } }] rc 0
[begin] rc 0
[create table bar { schema { int a } keys { "a" = a } constraints { "a" -> "foo":"a" on delete cascade } }] rc 0
[alter table foo { schema { int a } keys { "a" = a } }] rc 0
[commit] failed with rc 240 constraint error for table "bar" key "a" -> <"foo":"a">: parent key not found
