#!/usr/bin/env bash

# simple test to verify that new master does not block indefinitely when
# resuming a schema change that made zero progress from the previous master

source ${TESTSROOTDIR}/tools/runit_common.sh
source ${TESTSROOTDIR}/tools/cluster_utils.sh

set -ex

[ -z "${CLUSTER}" ] && { echo "Test requires a cluster"; exit 0; }

dbnm=$1
master=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'SELECT host FROM comdb2_cluster WHERE is_master="Y"'`

function timepart_stats
{
    cdb2sql ${CDB2_OPTIONS} $dbnm default "exec procedure sys.cmd.send('partitions')" | egrep -v "STARTTIME|LOW|HIGH|SOURCE_ID"
    cdb2sql ${CDB2_OPTIONS} $dbnm default "select name, period, retention, nshards, version,shard0name from comdb2_timepartitions "
    cdb2sql ${CDB2_OPTIONS} $dbnm default "select name, shardname from comdb2_timepartshards"
    cdb2sql ${CDB2_OPTIONS} --host MASTER $dbnm default "select name, arg1, arg2, arg3 from comdb2_timepartevents order by 1, 2"
}

starttime=$(get_timestamp 120)
cdb2sql ${CDB2_OPTIONS} $dbnm default "CREATE TABLE t14(a int, b int) PARTITIONED BY TIME PERIOD 'daily' RETENTION 2 START '${starttime}'"
cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t14 values (10,20), (30,40), (50,60)"
cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into '\$1_9ABA178A' values (111,111)"
cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into '\$0_528953B1' values (222,222)"
cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from t14 order by 1"

cdb2sql ${CDB2_OPTIONS} $dbnm default "ALTER TABLE t14 PARTITIONED BY NONE" &
waitpid=$!
sleep 2
set +e
for node in $CLUSTER ; do
    kill_restart_node $node &
done
set -e

for node in $CLUSTER;
do
	echo "Testing $node"
	cdb2sql ${CDB2_OPTIONS} --host $node $dbnm default "select * from t14 order by 1"
done
