#!/usr/bin/env bash

source ${TESTSROOTDIR}/tools/runit_common.sh
source ${TESTSROOTDIR}/tools/cluster_utils.sh

set -ex

[ -z "${CLUSTER}" ] && { echo "Test requires a cluster"; exit 0; }

dbnm=$1

test_partition_merge_resume() {
	# Given
	local starttime
	starttime=$(get_timestamp 120)
	cdb2sql ${CDB2_OPTIONS} $dbnm default "CREATE TABLE t14(a int, b int) PARTITIONED BY TIME PERIOD 'daily' RETENTION 2 START '${starttime}'"
	cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into t14 values (10,20), (30,40), (50,60)"
	cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into '\$1_9ABA178A' values (111,111)"
	cdb2sql ${CDB2_OPTIONS} $dbnm default "insert into '\$0_528953B1' values (222,222)"
	cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from t14 order by 1" > exp

	# When
	cdb2sql ${CDB2_OPTIONS} $dbnm default "ALTER TABLE t14 PARTITIONED BY NONE" &
	waitpid=$!
	sleep 2 # give the master node a bit time to get to the convert thread

	set +e
	for node in $CLUSTER ; do
		kill_restart_node $node &
	done
	wait $waitpid
	set -e

	sleep 5

	# Then
	for node in $CLUSTER ; do
		echo "testing $node"
		cdb2sql ${CDB2_OPTIONS} $dbnm default "select * from t14 order by 1" > out
		if ! diff exp out;
		then
			echo "FAILED: Unexpected select results after merge"
			echo "expected:"
			cat exp
			echo "observed:"
			cat out
			return 1
		fi
	done

	return 0
}

test_partition_merge_resume
