#!/usr/bin/env bash

source ${TESTSROOTDIR}/tools/runit_common.sh
source ${TESTSROOTDIR}/tools/cluster_utils.sh

set -ex

[ -z "${CLUSTER}" ] && { echo "Test requires a cluster"; exit 0; }

dbnm=$1

test_partition_merge_resume() {
	# Given
	local starttime
	starttime=$(get_timestamp 120)
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "exec procedure sys.cmd.send('debug_sleep_on_partition_merge on')"
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "create table t(a int) partitioned by time period 'daily' retention 2 start '${starttime}'"
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "insert into t values(1)"

	# When
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "alter table t partitioned by none" &
	sleep 1

	set +e
	for node in ${CLUSTER} ; do
		kill_restart_node ${node} &> /dev/null &
	done
	set -e

	until cdb2sql ${CDB2_OPTIONS} ${dbnm} default "select 1";
	do
		:
	done &> /dev/null

	# Then
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "select * from comdb2_timepartitions"

	# Cleanup
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "exec procedure sys.cmd.send('debug_sleep_on_partiton_merge off')"
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "drop table t"
}

test_partition_alter_resume() {
	# Given
	local starttime
	starttime=$(get_timestamp 120)
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "exec procedure sys.cmd.send('debug_sleep_on_alter on')"
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "create table t(a int) partitioned by time period 'daily' retention 2 start '${starttime}'"
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "insert into t values(1)"

	# When
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "alter table t add column j int" &
	sleep 1

	set +e
	for node in ${CLUSTER} ; do
		kill_restart_node ${node} &> /dev/null &
	done
	set -e

	until cdb2sql ${CDB2_OPTIONS} ${dbnm} default "select 1";
	do
		:
	done &> /dev/null

	# Then
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "select j from t" # Should not fail

	# Cleanup
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "exec procedure sys.cmd.send('debug_sleep_on_alter off')"
	cdb2sql ${CDB2_OPTIONS} ${dbnm} default "drop table t"
}

test_partition_merge_resume
test_partition_alter_resume
