#!/usr/bin/env bash
bash -n "$0" | exit 1

source $TESTSROOTDIR/tools/runstepper.sh

dbname=$1
if [[ -z $dbname ]] ; then
    echo dbname missing
    exit 1
fi

# verify the result
function verify
{
    # args
    typeset testname=$1

    cmd="diff ${testname}.expected ${testname}.output"
    $cmd > /dev/null

    if [[  $? -eq 0 ]]; then
        echo "passed $testname"
    else
        echo "failed $testname"
        echo "see diffs here: $HOSTNAME"
        echo "> diff -u ${PWD}/{$testname.expected,$testname.output}"
        echo
        exit 1
    fi

}

for transtest in `ls t*.trans` ; do
    testname=`echo $transtest | cut -d "." -f 1`
    output=$testname.output

    runstepper $dbname $transtest $output
    cat ${testname}.output | perl -pe "s/.n_writeops_done=([0-9]+)/rows inserted='\1'/; s/BLOCK2_SEQV2\(824\)/BLOCK_SEQ(800)/; s/OP #2 BLOCK_SEQ/OP #3 BLOCK_SEQ/; s/genid=\w+/genid=xxxx/;" > tmp
    mv tmp  ${testname}.output

    verify $testname
done

echo "Testcase passed."
exit 0
